# =========================================================
# Production Environment Configuration
# =========================================================

[environment]
base_url = https://demoblaze.com/
username = pavano1
password = test@123
env = production

[browser]
browser_name = chrome
headless = true
implicit_wait = 10
explicit_wait = 20
page_load_timeout = 60

[execution]
timeout = 60
retries = 2
workers = 2
parallel = true

[reporting]
screenshot = only-on-failure
html_report = true
allure_report = true
log_level = WARNING