# =========================================================
# Staging Environment Configuration
# =========================================================

[environment]
base_url = https://demoblaze.com/
username = pavano1
password = test@123
env = staging

[browser]
browser_name = chrome
headless = true
implicit_wait = 10
explicit_wait = 20
page_load_timeout = 45

[execution]
timeout = 45
retries = 2
workers = 4
parallel = true

[reporting]
screenshot = on
html_report = true
allure_report = true
log_level = INFO